// Whose phone is this? — POST /api/push/subscribe
//
// THE DEFECT
// `INSERT … ON CONFLICT (endpoint) DO UPDATE SET user_id = EXCLUDED.user_id`
// with no condition. The endpoint string alone was sufficient to take a
// subscription over: a user who knew another user's endpoint POSTed it with
// keys of their own, and the row moved — user_id reassigned, p256dh and auth
// replaced, HTTP 200. The victim then silently stopped receiving push
// notifications, with nothing on any screen to say why. `push_subscriptions`
// has no organization_id, so this crosses every tenant at once and the org
// write invariant cannot see it at all.
//
// WHAT MUST KEEP WORKING, and why the obvious fix is wrong
// A shared device is REAL on this product: one phone gets handed between crew,
// the second person signs in, and the row MUST follow the current user or the
// wrong person keeps getting the notifications. So "never re-point" is not
// available. The line drawn instead is between NAMING the subscription and
// PROVING it: the endpoint names it, the keys (p256dh + auth, generated by the
// browser for that subscription and not derivable from the endpoint) prove it.
//
// THE PROPERTIES
//   S1  A new endpoint always inserts. (Nothing here narrows first-time
//       subscription.)
//   S2  The owner may refresh their own row, keys included.
//   S3  A DIFFERENT user presenting the STORED keys re-points the row — the
//       shared-device case, preserved.
//   S4  A different user presenting the endpoint with keys of their own is
//       REFUSED, the row is byte-identical, and the refusal is VISIBLE (a
//       status, not a 200) — a 200 here would tell the attacker's client it is
//       subscribed while the victim's row silently changed, or tell an honest
//       client it succeeded when it did not.
//   S5  A refusal never destroys the victim's keys — the failure mode is "you
//       are not subscribed", never "nobody is".
//
// Executed against the real router over real HTTP with real JWTs, on the
// repo's SQLite-backed engine, reading the DATABASE after every call.

'use strict';

const express = require('express');
const http = require('http');

const { createPgSqlite } = require('./helpers/pg-sqlite');

const SCHEMA = `
  CREATE TABLE organizations (id INTEGER PRIMARY KEY, name TEXT);
  CREATE TABLE users (id INTEGER PRIMARY KEY, email TEXT, role TEXT, organization_id INTEGER);
  CREATE TABLE roles (name TEXT PRIMARY KEY, label TEXT, capabilities TEXT);
  CREATE TABLE push_subscriptions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    endpoint TEXT UNIQUE,
    p256dh TEXT,
    auth TEXT,
    user_agent TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
  );
  CREATE TABLE app_settings (key TEXT PRIMARY KEY, value TEXT);
`;

const engine = createPgSqlite(SCHEMA, {});
globalThis.__P86_PUSH_ENGINE__ = engine;

jest.mock('../server/db', () => ({ pool: globalThis.__P86_PUSH_ENGINE__.pool }));

// The push sender is not under test and must not reach the network. Only the
// shape the route uses is stubbed.
jest.mock('../server/push', () => ({
  isConfigured: () => true,
  getPublicKey: async () => 'test-public-key',
  ensureInit: async () => {},
  sendToUser: async () => ({ sent: 0 }),
}));

const { signToken, setRolePool, refreshRoleCache } = require('../server/auth');
const pushRoutes = require('../server/routes/push-routes');

let server, baseUrl;

const ENDPOINT = 'https://fcm.googleapis.com/fcm/send/cQK3v9Xr2Lm-victim-token';
const VICTIM_KEYS = { p256dh: 'VICTIM-P256DH-PUBLIC-KEY', auth: 'VICTIM-AUTH-SECRET' };
const ATTACKER_KEYS = { p256dh: 'ATTACKER-P256DH-KEY', auth: 'ATTACKER-AUTH-SECRET' };

const VICTIM = { id: 20, email: 'b@b.b', role: 'admin', organization_id: 2 };
const ATTACKER = { id: 10, email: 'a@a.a', role: 'admin', organization_id: 1 };

function seed() {
  engine.db.exec(`
    DELETE FROM push_subscriptions; DELETE FROM users;
    DELETE FROM roles; DELETE FROM organizations;
    INSERT INTO organizations (id, name) VALUES (1, 'Org A'), (2, 'Org B');
    INSERT INTO users (id, email, role, organization_id) VALUES
      (10, 'a@a.a', 'admin', 1), (20, 'b@b.b', 'admin', 2), (30, 'c@c.c', 'admin', 2);
    INSERT INTO roles (name, label, capabilities) VALUES
      ('admin', 'Admin', '["ESTIMATES_EDIT","ESTIMATES_VIEW","FINANCIALS_VIEW"]');
  `);
  setRolePool(engine.pool);
  return refreshRoleCache();
}

function seedSubscription(userId, endpoint, keys) {
  engine.db.prepare(
    `INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth, user_agent)
     VALUES (?, ?, ?, ?, ?)`
  ).run(userId, endpoint, keys.p256dh, keys.auth, 'seed-agent');
}

function snapshot(endpoint) {
  return JSON.stringify(engine.db.prepare(
    `SELECT user_id, endpoint, p256dh, auth FROM push_subscriptions WHERE endpoint = ?`
  ).all(endpoint));
}

function row(endpoint) {
  const r = engine.db.prepare(
    `SELECT user_id, p256dh, auth, user_agent FROM push_subscriptions WHERE endpoint = ?`
  ).all(endpoint);
  return r.length ? r[0] : null;
}

async function subscribe(user, endpoint, keys) {
  const res = await fetch(baseUrl + '/api/push/subscribe', {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'user-agent': 'jest-agent',
      authorization: 'Bearer ' + signToken(user)
    },
    body: JSON.stringify({ endpoint, keys })
  });
  let json = null;
  try { json = await res.json(); } catch (e) { /* non-JSON */ }
  return { status: res.status, body: json };
}

beforeAll((done) => {
  const app = express();
  app.use(express.json());
  app.use('/api/push', pushRoutes);
  server = http.createServer(app);
  server.listen(0, '127.0.0.1', () => {
    baseUrl = 'http://127.0.0.1:' + server.address().port;
    done();
  });
});
afterAll((done) => { server.close(() => done()); });
beforeEach(() => seed());

describe('PATH S — POST /api/push/subscribe', () => {
  test('S1 — a brand-new endpoint always inserts', async () => {
    const res = await subscribe(ATTACKER, 'https://fcm.googleapis.com/fcm/send/fresh', ATTACKER_KEYS);
    expect(res.status).toBe(200);
    expect(row('https://fcm.googleapis.com/fcm/send/fresh').user_id).toBe(10);
  });

  test('S2 — the owner refreshes their own row, rotated keys and all', async () => {
    seedSubscription(20, ENDPOINT, VICTIM_KEYS);
    const rotated = { p256dh: 'VICTIM-ROTATED-KEY', auth: 'VICTIM-ROTATED-AUTH' };
    const res = await subscribe(VICTIM, ENDPOINT, rotated);
    expect(res.status).toBe(200);
    const r = row(ENDPOINT);
    expect(r.user_id).toBe(20);
    expect(r.p256dh).toBe('VICTIM-ROTATED-KEY');
    // The user_agent refresh is what makes this a real re-registration.
    expect(r.user_agent).toBe('jest-agent');
  });

  test('S3 — THE SHARED DEVICE STILL WORKS: a second user presenting the stored keys takes the row', async () => {
    // This is the case the original unconditional DO UPDATE existed for, and
    // it must not regress. The browser hands back the subscription the first
    // session created — endpoint AND keys — so the second user can prove
    // possession without anyone doing anything unusual.
    seedSubscription(20, ENDPOINT, VICTIM_KEYS);
    const res = await subscribe({ id: 30, email: 'c@c.c', role: 'admin', organization_id: 2 },
                                ENDPOINT, VICTIM_KEYS);
    expect(res.status).toBe(200);
    expect(row(ENDPOINT).user_id).toBe(30);
  });

  test('S4 — knowing the endpoint is NOT enough: the takeover is refused and the row is byte-identical', async () => {
    seedSubscription(20, ENDPOINT, VICTIM_KEYS);
    const before = snapshot(ENDPOINT);
    const res = await subscribe(ATTACKER, ENDPOINT, ATTACKER_KEYS);
    // VISIBLY refused. A 200 here is the whole defect: it reports success
    // while the notifications go somewhere the caller cannot see.
    expect(res.status).toBe(409);
    // Read the DATABASE, not the response.
    expect(snapshot(ENDPOINT)).toBe(before);
    expect(row(ENDPOINT).user_id).toBe(20);
  });

  test('S5 — a refused attempt leaves the victim still subscribed with their own keys', async () => {
    seedSubscription(20, ENDPOINT, VICTIM_KEYS);
    await subscribe(ATTACKER, ENDPOINT, ATTACKER_KEYS);
    const r = row(ENDPOINT);
    expect(r.p256dh).toBe(VICTIM_KEYS.p256dh);
    expect(r.auth).toBe(VICTIM_KEYS.auth);
    // Exactly one row: the refusal did not create a duplicate for the attacker.
    expect(engine.count('SELECT id FROM push_subscriptions')).toBe(1);
  });

  test('S4b — half the proof is not proof: the right p256dh with the wrong auth is refused', async () => {
    // Stated because a fix that compared only ONE of the two values would pass
    // S4 above while leaving the takeover open to anyone who learned the
    // public key — p256dh is the PUBLIC half of the pair.
    seedSubscription(20, ENDPOINT, VICTIM_KEYS);
    const before = snapshot(ENDPOINT);
    const res = await subscribe(ATTACKER, ENDPOINT,
      { p256dh: VICTIM_KEYS.p256dh, auth: 'GUESSED-AUTH' });
    expect(res.status).toBe(409);
    expect(snapshot(ENDPOINT)).toBe(before);
  });

  test('a malformed subscription is still rejected before any of this', async () => {
    const res = await subscribe(ATTACKER, 'http://not-https/endpoint', ATTACKER_KEYS);
    expect(res.status).toBe(400);
    expect(engine.count('SELECT id FROM push_subscriptions')).toBe(0);
  });
});
