// SINGLE-TENANT INERTNESS, PROVED DIFFERENTIALLY AGAINST THE PRE-REPAIR COMMIT.
//
// ── THE CLAIM THIS FILE REPLACES ──────────────────────────────────────────
// "With one organisation, every row matches one arm of the predicate or the
// other, so the counts are unchanged to the digit." That sentence is TRUE, and
// it is still only a sentence. Production has real money in it and exactly one
// organisation, which means the repairs in `f829e682` and `3e2c70a2` have no
// upside there at all — their entire value is for org #2. So the standard they
// have to meet today is not "probably fine": it is BYTE-IDENTICAL, and the
// difference between those two is a measurement.
//
// ── HOW THE GOLDEN WAS PRODUCED, AND WHY THAT MATTERS ─────────────────────
// `test/golden/single-tenant-answers.json` was NOT generated from this tree. It
// was generated by checking out `69f2cabd` — the commit BEFORE any of the
// thirteen predicates landed — into a detached worktree, copying in this file
// and the fixture it needs, and running it there. Every answer in it is what
// the UNREPAIRED code returned.
//
// So a passing run here says something a self-generated golden never could:
//
//   FOR A ONE-ORGANISATION DATABASE, TODAY'S CODE AND THE CODE FROM BEFORE THE
//   REPAIRS RETURN THE SAME BYTES, FOR EVERY DOOR, ON THE SAME INPUTS.
//
// A golden regenerated from HEAD would assert only that HEAD equals itself.
// That is the failure mode this file exists to avoid, and it is why the golden
// carries `generated_from` and why the test below refuses to run if that field
// is not the pre-repair SHA.
//
// ── WHY THE FIXTURE HAS A NULL-ORG ROW IN IT ──────────────────────────────
// `ai_messages` HOLDS UN-STAMPED ROWS IN PRODUCTION. server/db.js:656 adds the
// column late, :721 backfills it from the author's user row at every boot, and
// :761 guesses behind NEVER_MULTI_ORG. Every repaired predicate is therefore
// written as `(organization_id = $n OR organization_id IS NULL)`, and if that
// tolerance arm were missing or wrong, John's own token dashboard would move
// the day it deployed. The one-org world here contains un-stamped rows for
// exactly that reason: this file is the thing that would have caught it.
//
// ── WHAT A FAILURE HERE MEANS ─────────────────────────────────────────────
// Not "a tenant leaked" — this world has one tenant and nothing to leak to. It
// means A REPAIR CHANGED WHAT JOHN SEES. That is the more urgent failure of the
// two right now, and it is the one with a live pilot behind it.
'use strict';

process.env.JWT_SECRET = process.env.JWT_SECRET
  || 'test-only-secret-with-at-least-32-characters-of-padding';

const fs = require('fs');
const path = require('path');
const express = require('express');
const http = require('http');

const TWO = require('./helpers/two-org');
const { ORG_A } = TWO;

const GOLDEN_PATH = path.join(__dirname, 'golden', 'single-tenant-answers.json');

// The commit the golden was captured at: the parent of the first repair.
const PRE_REPAIR_SHA = '69f2cabd';

const RECENT = '2026-09-01 12:00:00';

// ── THE ONE-ORGANISATION WORLD ────────────────────────────────────────────
// Org A plus un-stamped legacy rows. No org B, because org B does not exist in
// production and the question here is what production does.
const ID = (t, tag) => TWO.idFor(t, tag);

const OVERLAY = {
  organizations: [{ id: ORG_A, name: 'Affiliate Alpha', slug: 'alpha' }],
  roles: [
    { name: 'admin', label: 'Org Admin', capabilities: JSON.stringify(['ROLES_MANAGE', 'ADMIN_METRICS', 'USERS_MANAGE', 'INSIGHTS_VIEW', 'ESTIMATES_VIEW', 'JOBS_VIEW', 'LEADS_VIEW', 'CLIENTS_VIEW', 'SUBS_VIEW', 'SCHEDULE_VIEW', 'FILES_VIEW', 'REPORTS_VIEW', 'FINANCIALS_VIEW']) },
    { name: 'system_admin', label: 'System Admin', capabilities: JSON.stringify(['ROLES_MANAGE', 'ADMIN_METRICS', 'USERS_MANAGE', 'SYSTEM_ADMIN', 'INSIGHTS_VIEW']) },
  ],
  users: [
    { id: ID('users', 'A'), organization_id: ORG_A, email: 'a@a.a', name: 'A Admin', role: 'admin', active: 1 },
    { id: ID('users', 'N'), organization_id: null, email: 'n@n.n', name: 'Orphan', role: 'admin', active: 1 },
  ],
  estimates: [
    { id: ID('estimates', 'A'), organization_id: ORG_A, owner_id: ID('users', 'A'), data: JSON.stringify({ title: 'Alpha Re-roof', totalProposal: 250, status: 'sent', lines: [{ id: 'l1', description: 'seamless gutters 6in', qty: 40, unit: 'lf', unitCost: 11, markup: 42 }] }), is_locked: 0, updated_at: RECENT },
    { id: ID('estimates', 'N'), organization_id: null, owner_id: null, data: JSON.stringify({ title: 'Legacy Re-roof', totalProposal: 100, status: 'sent', lines: [{ id: 'l1', description: 'legacy gutters', qty: 4, unit: 'lf', unitCost: 9, markup: 40 }] }), is_locked: 0, updated_at: RECENT },
  ],
  jobs: [
    { id: ID('jobs', 'A'), organization_id: ORG_A, owner_id: ID('users', 'A'), data: JSON.stringify({ jobNumber: 'J-A', title: 'Alpha Job', buildings: [{ id: 'b1', name: 'Building One', pctComplete: 50 }], phases: [{ id: 'p1', buildingId: 'b1', name: 'Phase', phaseBudget: 1000, asSoldRevenue: 1000, pctComplete: 50 }] }) },
    { id: ID('jobs', 'N'), organization_id: null, owner_id: null, data: JSON.stringify({ jobNumber: 'J-N', title: 'Legacy Job', buildings: [], phases: [] }) },
  ],
  clients: [
    { id: ID('clients', 'A'), organization_id: ORG_A, name: 'Alpha HOA', agent_notes: '[]', client_type: 'hoa', city: 'Orlando', activation_status: 'active' },
    { id: ID('clients', 'N'), organization_id: null, name: 'Legacy Client', agent_notes: '[]', client_type: 'hoa', city: 'Orlando', activation_status: 'active' },
  ],
  attachments: [
    { id: ID('attachments', 'A'), organization_id: ORG_A, entity_type: 'estimate', entity_id: ID('estimates', 'A'), filename: 'alpha.pdf', mime_type: 'application/pdf', extracted_text: 'ALPHA scope text', uploaded_by: ID('users', 'A'), web_key: 'k/a' },
  ],
  qb_cost_lines: [
    { id: ID('qb_cost_lines', 'A'), organization_id: ORG_A, job_id: ID('jobs', 'A'), amount: 150, vendor: 'Alpha Supply' },
    { id: ID('qb_cost_lines', 'N'), organization_id: null, job_id: ID('jobs', 'A'), amount: 7, vendor: 'Legacy Supply' },
  ],
  // THE ROWS THAT MAKE THIS TEST WORTH RUNNING. Two stamped, ONE UN-STAMPED —
  // the shape production actually has, and the only shape in which the
  // tolerance arm is load-bearing.
  ai_messages: [
    { id: ID('ai_messages', 'A'), organization_id: ORG_A, entity_type: 'estimate', estimate_id: ID('estimates', 'A'), user_id: ID('users', 'A'), session_id: ID('ai_sessions', 'A'), role: 'assistant', content: 'alpha turn', model: 'claude-sonnet-5', input_tokens: 1200, output_tokens: 340, tool_use_count: 1, tool_uses: '[{"name":"read_jobs"}]', created_at: RECENT },
    { id: ID('ai_messages', 'N'), organization_id: null, entity_type: 'estimate', estimate_id: ID('estimates', 'A'), user_id: ID('users', 'A'), session_id: ID('ai_sessions', 'A'), role: 'user', content: 'legacy un-stamped turn', model: 'claude-sonnet-5', input_tokens: 80, output_tokens: 9, tool_use_count: 0, tool_uses: '[]', created_at: RECENT },
  ],
  managed_agent_registry: [
    { agent_key: 'job', organization_id: ORG_A, anthropic_agent_id: 'agt_alpha', model: 'claude-sonnet-5', tool_count: 40, skill_count: 2 },
    { agent_key: 'assistant', organization_id: null, anthropic_agent_id: 'agt_orphan', model: 'claude-sonnet-5', tool_count: 10, skill_count: 0 },
  ],
};

const engine = TWO.buildEngine({ overlay: OVERLAY, withB: false });

globalThis.__P86_NOOP_ACTIVE__ = engine;
globalThis.__P86_NOOP_POOL__ = {
  query: (...a) => globalThis.__P86_NOOP_ACTIVE__.pool.query(...a),
  connect: (...a) => globalThis.__P86_NOOP_ACTIVE__.pool.connect(...a),
};
jest.mock('../server/db', () => ({ pool: globalThis.__P86_NOOP_POOL__ }));

jest.mock('@anthropic-ai/sdk', () => {
  function FakeAnthropic() {
    return {
      messages: {},
      beta: { agents: { retrieve: async () => { throw Object.assign(new Error('no network'), { status: 404 }); } } },
    };
  }
  FakeAnthropic.toFile = async () => ({});
  return Object.assign(FakeAnthropic, { toFile: FakeAnthropic.toFile, default: FakeAnthropic });
});

// ── WHY THE CLOCK IS FAKE FOR THE DURATION OF THESE REQUIRES ──────────────
// server/routes/admin-agents-routes.js:4821-4822 arms a setTimeout AND a
// setInterval AT MODULE LOAD — a background reference-link refresher whose
// handle is, by its own comment, "intentionally not stored" because "process
// exit cleans up". That is fine for a server and fatal for a test worker: the
// interval holds the event loop open forever, jest gives up waiting and
// FORCE-EXITS, and a force-exited worker can truncate a failure report.
//
// Faking the clock across the require and then handing it back drops those two
// timers with it. This is done here rather than by changing the router, because
// the router's behaviour in production is correct and this wave is not allowed
// to change production behaviour to make a test tidy.
jest.useFakeTimers();
const { signToken, setRolePool, refreshRoleCache } = require('../server/auth');
const aiRoutes = require('../server/routes/ai-routes');
const adminAgentsRoutes = require('../server/routes/admin-agents-routes');
jest.useRealTimers();
const I = aiRoutes.internals;

// ── the doors ─────────────────────────────────────────────────────────────
const TOOL_ACCESSORS = ['estimateTools', 'jobTools', 'clientTools', 'staffTools',
  'subtaskTools', 'memoryTools', 'projectInlineTools', 'watchTools',
  'payloadTools', 'readTools', 'wave3Tools'];

function publishedToolNames() {
  const s = new Set();
  for (const g of TOOL_ACCESSORS) for (const t of (I[g]() || [])) if (t && t.name) s.add(t.name);
  for (const n of I.ALLOWED_AUTO_TIER_TOOLS) s.add(n);
  for (const n of I.ORGLESS_ALLOWED_TOOLS) s.add(n);
  return [...s].sort();
}

const RECIPES = {
  read_past_estimate_lines:  { q: 'gutters', days: 1825 },
  read_past_estimates:       { days: 1825, limit: 50 },
  read_clients:              { limit: 100 },
  read_entity:               { entity_type: 'client', id: ID('clients', 'A'), depth: 'full' },
  read_attachment_text:      { attachment_id: ID('attachments', 'A') },
  read_qb_cost_lines:        { jobId: ID('jobs', 'A') },
  read_building_breakdown:   { jobId: ID('jobs', 'A') },
  read_job_pct_audit:        { jobId: ID('jobs', 'A') },
  read_active_lines:         { estimate_id: ID('estimates', 'A') },
  read_existing_clients:     { query: 'a' },
  read_existing_leads:       { query: 'a' },
  read_metrics:              { range: '7d' },
  read_recent_conversations: { limit: 20 },
  read_materials:            { q: 'a' },
  read_purchase_history:     { days: 365 },
  search_entities:           { entity_type: 'client', q: 'a' },
  search_my_kb:              { q: 'text' },
  search_org_kb:             { q: 'text' },
  search_my_sessions:        { query: 'alpha' },
  search_reference_sheet:    { q: 'a' },
  recall:                    { query: 'alpha' },
  find_entities_near:        { lat: 28.5, lng: -81.4, radius_miles: 50 },
};

// The write tools mint ids from Date.now(); they are excluded here for the same
// reason they are ledgered in test/tenant-conformance.test.js, and named rather
// than filtered by a shape guess.
const MINTS_AN_ID = ['create_property', 'remember'];

const UNKNOWN_RE = /^Unknown (?:staff |approval-tier staff |intake read |memory |Wave 3 |project-inline )?tool:/;

const ctx = () => ({
  userId: ID('users', 'A'), orgId: ORG_A,
  user: { id: ID('users', 'A'), organization_id: ORG_A, role: 'admin', email: 'a@a.a' },
});

let server, baseUrl;

async function httpGet(url, user) {
  const res = await fetch(baseUrl + url, {
    // `connection: close` is not decoration. undici keeps its sockets alive, so
    // without it the server has a live connection after the last assertion,
    // `server.close()` never calls back, and jest force-exits the worker — and
    // a force-exited worker can TRUNCATE A FAILURE REPORT. The suite would
    // still be "passing"; it just might stop being able to tell you when it
    // isn't. That is the one failure mode a guard cannot have.
    headers: { authorization: 'Bearer ' + signToken(user), connection: 'close' },
  });
  let body = null;
  try { body = await res.json(); } catch (e) { body = null; }
  return { status: res.status, body };
}

// Absolute time out — a golden captured on another day must still compare.
function stable(s) {
  return String(s)
    .replace(/\d{4}-\d{2}-\d{2}([T ]\d{2}:\d{2}(:\d{2})?(\.\d+)?Z?)?/g, '<TS>')
    .replace(/\b(Mon|Tue|Wed|Thu|Fri|Sat|Sun)\b[^,\n"]{0,24}/g, '<DAY>')
    .replace(/\b\d+\s*(seconds?|minutes?|hours?|days?|weeks?|months?|years?)\s*(ago|from now)/gi, '<REL>');
}

// ── the recording ─────────────────────────────────────────────────────────
async function record() {
  const out = {};

  // THE AGENT SURFACE.
  for (const name of publishedToolNames()) {
    if (MINTS_AN_ID.indexOf(name) !== -1) continue;
    let s;
    try { s = TWO.flatten(await I.execAgentTool(name, RECIPES[name] || {}, ctx())); }
    catch (e) { s = 'THREW: ' + (e && e.message); }
    if (s.startsWith('THREW: ') && UNKNOWN_RE.test(s.slice(7))) continue;   // not dispatched here
    out['tool:' + name] = stable(s);
  }

  // THE ADMIN CONSOLE — the surface all three of the L1/L2/L3 repairs landed on.
  const admin = { id: ID('users', 'A'), email: 'a@a.a', name: 'A Admin', role: 'admin', organization_id: ORG_A };
  for (const [label, url] of [
    ['metrics', '/api/admin/agents/metrics?range=7d'],
    ['conversations', '/api/admin/agents/conversations?limit=20'],
    ['managed', '/api/admin/agents/managed'],
    ['managed_audit', '/api/admin/agents/managed/audit'],
  ]) {
    const r = await httpGet(url, admin);
    out['route:' + label] = stable(r.status + ' ' + JSON.stringify(r.body));
  }
  return out;
}

beforeAll((done) => {
  const app = express();
  app.use(express.json({ limit: '10mb' }));
  app.use('/api/ai', aiRoutes);
  app.use('/api/admin/agents', adminAgentsRoutes);
  setRolePool(engine.pool);
  refreshRoleCache().then(() => {
    server = http.createServer(app);
    server.listen(0, '127.0.0.1', () => {
      baseUrl = 'http://127.0.0.1:' + server.address().port;
      done();
    });
  });
});
afterAll((done) => {
  // closeAllConnections FIRST. `fetch` (undici) holds its sockets open with
  // keep-alive, so `server.close()` alone waits for a connection that will
  // never end on its own and the worker never exits — which jest reports as
  // "A worker process has failed to exit gracefully" and then FORCE-EXITS,
  // and a force-exited worker can truncate a failure report. A suite whose
  // failures might not be printed is worse than a slow one.
  if (typeof server.closeAllConnections === 'function') server.closeAllConnections();
  server.close(() => done());
});

// ── CAPTURE MODE ──────────────────────────────────────────────────────────
// Set P86_CAPTURE_GOLDEN=1 to WRITE the golden instead of checking it. This is
// how the file was produced inside a `69f2cabd` worktree. It is deliberately an
// env var and not the default: a golden that regenerates itself whenever it
// disagrees is not a golden, it is a rubber stamp.
const CAPTURING = process.env.P86_CAPTURE_GOLDEN === '1';

describe('single-tenant inertness, against the pre-repair commit', () => {
  test(CAPTURING ? 'CAPTURE the golden' : 'every door answers exactly what 69f2cabd answered', async () => {
    const now = await record();

    if (CAPTURING) {
      fs.mkdirSync(path.dirname(GOLDEN_PATH), { recursive: true });
      fs.writeFileSync(GOLDEN_PATH, JSON.stringify({
        generated_from: process.env.P86_CAPTURE_SHA || 'UNKNOWN',
        note: 'Captured by running this file inside a detached worktree at the named commit. Do NOT regenerate from HEAD.',
        answers: now,
      }, null, 1) + '\n');
      expect(Object.keys(now).length).toBeGreaterThan(40);
      return;
    }

    const golden = JSON.parse(fs.readFileSync(GOLDEN_PATH, 'utf8'));

    // A golden captured from HEAD proves only that HEAD equals itself.
    expect(golden.generated_from).toBe(PRE_REPAIR_SHA);

    // Per DOOR, never a rate: the diff names every door whose bytes moved.
    const moved = [];
    for (const k of Object.keys(golden.answers)) {
      if (golden.answers[k] !== now[k]) {
        moved.push(k + '\n    then: ' + String(golden.answers[k]).slice(0, 220)
                     + '\n    now : ' + String(now[k]).slice(0, 220));
      }
    }
    expect(moved).toEqual([]);

    // And nothing appeared or vanished. A door that stopped answering would
    // otherwise pass the loop above by not being compared at all.
    expect(Object.keys(now).sort()).toEqual(Object.keys(golden.answers).sort());
  }, 120000);

  test('the golden covers both surfaces, and says how many doors', () => {
    if (CAPTURING) return;
    const golden = JSON.parse(fs.readFileSync(GOLDEN_PATH, 'utf8'));
    const keys = Object.keys(golden.answers);
    expect(keys.filter((k) => k.startsWith('tool:')).length).toBeGreaterThan(40);
    // The four admin-console doors the L1/L2/L3 repairs landed on.
    expect(keys.filter((k) => k.startsWith('route:')).sort())
      .toEqual(['route:conversations', 'route:managed', 'route:managed_audit', 'route:metrics']);
  });

  test('the un-stamped legacy row is PRESENT — without it the tolerance arm is never exercised', () => {
    const rows = engine.all('SELECT organization_id FROM ai_messages');
    expect(rows.some((r) => r.organization_id === null)).toBe(true);
    expect(rows.some((r) => r.organization_id === ORG_A)).toBe(true);
  });
});
