// SINGLE-TENANT INERTNESS, PROVED DIFFERENTIALLY AGAINST THE PRE-REPAIR COMMIT.
//
// ── THE CLAIM THIS FILE REPLACES ──────────────────────────────────────────
// "With one organisation, every row matches one arm of the predicate or the
// other, so the counts are unchanged to the digit." That sentence is TRUE, and
// it is still only a sentence. Production has real money in it and exactly one
// organisation, which means the repairs in `f829e682` and `3e2c70a2` have no
// upside there at all — their entire value is for org #2. So the standard they
// have to meet today is not "probably fine": it is BYTE-IDENTICAL, and the
// difference between those two is a measurement.
//
// ── HOW THE GOLDEN WAS PRODUCED, AND WHY THAT MATTERS ─────────────────────
// `test/golden/single-tenant-answers.json` was NOT generated from this tree. It
// was generated by checking out `69f2cabd` — the commit BEFORE any of the
// thirteen predicates landed — into a detached worktree, copying in this file
// and the fixture it needs, and running it there. Every answer in it is what
// the UNREPAIRED code returned.
//
// So a passing run here says something a self-generated golden never could:
//
//   FOR A ONE-ORGANISATION DATABASE, TODAY'S CODE AND THE CODE FROM BEFORE THE
//   REPAIRS RETURN THE SAME BYTES, FOR EVERY DOOR, ON THE SAME INPUTS.
//
// A golden regenerated from HEAD would assert only that HEAD equals itself.
// That is the failure mode this file exists to avoid, and it is why the golden
// carries `generated_from` and why the test below refuses to run if that field
// is not the pre-repair SHA.
//
// ── WHY THE FIXTURE HAS A NULL-ORG ROW IN IT ──────────────────────────────
// `ai_messages` HOLDS UN-STAMPED ROWS IN PRODUCTION. server/db.js:656 adds the
// column late, :721 backfills it from the author's user row at every boot, and
// :761 guesses behind NEVER_MULTI_ORG. Every repaired predicate is therefore
// written as `(organization_id = $n OR organization_id IS NULL)`, and if that
// tolerance arm were missing or wrong, John's own token dashboard would move
// the day it deployed. The one-org world here contains un-stamped rows for
// exactly that reason: this file is the thing that would have caught it.
//
// ── WHAT A FAILURE HERE MEANS ─────────────────────────────────────────────
// Not "a tenant leaked" — this world has one tenant and nothing to leak to. It
// means A REPAIR CHANGED WHAT JOHN SEES. That is the more urgent failure of the
// two right now, and it is the one with a live pilot behind it.
'use strict';

process.env.JWT_SECRET = process.env.JWT_SECRET
  || 'test-only-secret-with-at-least-32-characters-of-padding';

const fs = require('fs');
const path = require('path');
const express = require('express');
const http = require('http');

const TWO = require('./helpers/two-org');
const { ORG_A } = TWO;

const GOLDEN_PATH = path.join(__dirname, 'golden', 'single-tenant-answers.json');

// The commit the golden was captured at: the parent of the first repair.
const PRE_REPAIR_SHA = '69f2cabd';

// FIVE DAYS OLD, AND RELATIVE FOR THE SAME REASON T_OLD IS (see two-org.js).
// This was the literal '2026-09-01 12:00:00'. The doors below read these rows
// back through `datetime('now','-7 days')`, so what has to stay constant is the
// AGE, not the date — and pinned to that literal these rows were about 30 hours
// from ageing out of the metrics window, which moves four doors' bytes with no
// code change behind it. Five days is the age the golden was captured at, so
// the recorded answers keep the window membership they were recorded with:
// inside 7 days, and not so fresh that a narrower window would now include a
// row the golden recorded as excluded.
const RECENT = TWO.daysAgo(5);

// ── THE ONE-ORGANISATION WORLD ────────────────────────────────────────────
// Org A plus un-stamped legacy rows. No org B, because org B does not exist in
// production and the question here is what production does.
const ID = (t, tag) => TWO.idFor(t, tag);

const OVERLAY = {
  organizations: [{ id: ORG_A, name: 'Affiliate Alpha', slug: 'alpha' }],
  roles: [
    { name: 'admin', label: 'Org Admin', capabilities: JSON.stringify(['ROLES_MANAGE', 'ADMIN_METRICS', 'USERS_MANAGE', 'INSIGHTS_VIEW', 'ESTIMATES_VIEW', 'JOBS_VIEW', 'LEADS_VIEW', 'CLIENTS_VIEW', 'SUBS_VIEW', 'SCHEDULE_VIEW', 'FILES_VIEW', 'REPORTS_VIEW', 'FINANCIALS_VIEW']) },
    { name: 'system_admin', label: 'System Admin', capabilities: JSON.stringify(['ROLES_MANAGE', 'ADMIN_METRICS', 'USERS_MANAGE', 'SYSTEM_ADMIN', 'INSIGHTS_VIEW']) },
  ],
  users: [
    { id: ID('users', 'A'), organization_id: ORG_A, email: 'a@a.a', name: 'A Admin', role: 'admin', active: 1 },
    { id: ID('users', 'N'), organization_id: null, email: 'n@n.n', name: 'Orphan', role: 'admin', active: 1 },
  ],
  estimates: [
    { id: ID('estimates', 'A'), organization_id: ORG_A, owner_id: ID('users', 'A'), data: JSON.stringify({ title: 'Alpha Re-roof', totalProposal: 250, status: 'sent', lines: [{ id: 'l1', description: 'seamless gutters 6in', qty: 40, unit: 'lf', unitCost: 11, markup: 42 }] }), is_locked: 0, updated_at: RECENT },
    { id: ID('estimates', 'N'), organization_id: null, owner_id: null, data: JSON.stringify({ title: 'Legacy Re-roof', totalProposal: 100, status: 'sent', lines: [{ id: 'l1', description: 'legacy gutters', qty: 4, unit: 'lf', unitCost: 9, markup: 40 }] }), is_locked: 0, updated_at: RECENT },
  ],
  jobs: [
    { id: ID('jobs', 'A'), organization_id: ORG_A, owner_id: ID('users', 'A'), data: JSON.stringify({ jobNumber: 'J-A', title: 'Alpha Job', buildings: [{ id: 'b1', name: 'Building One', pctComplete: 50 }], phases: [{ id: 'p1', buildingId: 'b1', name: 'Phase', phaseBudget: 1000, asSoldRevenue: 1000, pctComplete: 50 }] }) },
    { id: ID('jobs', 'N'), organization_id: null, owner_id: null, data: JSON.stringify({ jobNumber: 'J-N', title: 'Legacy Job', buildings: [], phases: [] }) },
  ],
  clients: [
    { id: ID('clients', 'A'), organization_id: ORG_A, name: 'Alpha HOA', agent_notes: '[]', client_type: 'hoa', city: 'Orlando', activation_status: 'active' },
    { id: ID('clients', 'N'), organization_id: null, name: 'Legacy Client', agent_notes: '[]', client_type: 'hoa', city: 'Orlando', activation_status: 'active' },
  ],
  attachments: [
    { id: ID('attachments', 'A'), organization_id: ORG_A, entity_type: 'estimate', entity_id: ID('estimates', 'A'), filename: 'alpha.pdf', mime_type: 'application/pdf', extracted_text: 'ALPHA scope text', uploaded_by: ID('users', 'A'), web_key: 'k/a' },
  ],
  qb_cost_lines: [
    { id: ID('qb_cost_lines', 'A'), organization_id: ORG_A, job_id: ID('jobs', 'A'), amount: 150, vendor: 'Alpha Supply' },
    { id: ID('qb_cost_lines', 'N'), organization_id: null, job_id: ID('jobs', 'A'), amount: 7, vendor: 'Legacy Supply' },
  ],
  // THE ROWS THAT MAKE THIS TEST WORTH RUNNING. Two stamped, ONE UN-STAMPED —
  // the shape production actually has, and the only shape in which the
  // tolerance arm is load-bearing.
  ai_messages: [
    { id: ID('ai_messages', 'A'), organization_id: ORG_A, entity_type: 'estimate', estimate_id: ID('estimates', 'A'), user_id: ID('users', 'A'), session_id: ID('ai_sessions', 'A'), role: 'assistant', content: 'alpha turn', model: 'claude-sonnet-5', input_tokens: 1200, output_tokens: 340, tool_use_count: 1, tool_uses: '[{"name":"read_jobs"}]', created_at: RECENT },
    { id: ID('ai_messages', 'N'), organization_id: null, entity_type: 'estimate', estimate_id: ID('estimates', 'A'), user_id: ID('users', 'A'), session_id: ID('ai_sessions', 'A'), role: 'user', content: 'legacy un-stamped turn', model: 'claude-sonnet-5', input_tokens: 80, output_tokens: 9, tool_use_count: 0, tool_uses: '[]', created_at: RECENT },
  ],
  managed_agent_registry: [
    { agent_key: 'job', organization_id: ORG_A, anthropic_agent_id: 'agt_alpha', model: 'claude-sonnet-5', tool_count: 40, skill_count: 2 },
    { agent_key: 'assistant', organization_id: null, anthropic_agent_id: 'agt_orphan', model: 'claude-sonnet-5', tool_count: 10, skill_count: 0 },
  ],
};

const engine = TWO.buildEngine({ overlay: OVERLAY, withB: false });

globalThis.__P86_NOOP_ACTIVE__ = engine;
globalThis.__P86_NOOP_POOL__ = {
  query: (...a) => globalThis.__P86_NOOP_ACTIVE__.pool.query(...a),
  connect: (...a) => globalThis.__P86_NOOP_ACTIVE__.pool.connect(...a),
};
jest.mock('../server/db', () => ({ pool: globalThis.__P86_NOOP_POOL__ }));

jest.mock('@anthropic-ai/sdk', () => {
  function FakeAnthropic() {
    return {
      messages: {},
      beta: { agents: { retrieve: async () => { throw Object.assign(new Error('no network'), { status: 404 }); } } },
    };
  }
  FakeAnthropic.toFile = async () => ({});
  return Object.assign(FakeAnthropic, { toFile: FakeAnthropic.toFile, default: FakeAnthropic });
});

// ── WHY THE CLOCK IS FAKE FOR THE DURATION OF THESE REQUIRES ──────────────
// server/routes/admin-agents-routes.js:4821-4822 arms a setTimeout AND a
// setInterval AT MODULE LOAD — a background reference-link refresher whose
// handle is, by its own comment, "intentionally not stored" because "process
// exit cleans up". That is fine for a server and fatal for a test worker: the
// interval holds the event loop open forever, jest gives up waiting and
// FORCE-EXITS, and a force-exited worker can truncate a failure report.
//
// Faking the clock across the require and then handing it back drops those two
// timers with it. This is done here rather than by changing the router, because
// the router's behaviour in production is correct and this wave is not allowed
// to change production behaviour to make a test tidy.
jest.useFakeTimers();
const { signToken, setRolePool, refreshRoleCache } = require('../server/auth');
const aiRoutes = require('../server/routes/ai-routes');
const adminAgentsRoutes = require('../server/routes/admin-agents-routes');
jest.useRealTimers();
const I = aiRoutes.internals;

// ── the doors ─────────────────────────────────────────────────────────────
const TOOL_ACCESSORS = ['estimateTools', 'jobTools', 'clientTools', 'staffTools',
  'subtaskTools', 'memoryTools', 'projectInlineTools', 'watchTools',
  'payloadTools', 'readTools', 'wave3Tools'];

function publishedToolNames() {
  const s = new Set();
  for (const g of TOOL_ACCESSORS) for (const t of (I[g]() || [])) if (t && t.name) s.add(t.name);
  for (const n of I.ALLOWED_AUTO_TIER_TOOLS) s.add(n);
  for (const n of I.ORGLESS_ALLOWED_TOOLS) s.add(n);
  return [...s].sort();
}

const RECIPES = {
  read_past_estimate_lines:  { q: 'gutters', days: 1825 },
  read_past_estimates:       { days: 1825, limit: 50 },
  read_clients:              { limit: 100 },
  read_entity:               { entity_type: 'client', id: ID('clients', 'A'), depth: 'full' },
  read_attachment_text:      { attachment_id: ID('attachments', 'A') },
  read_qb_cost_lines:        { jobId: ID('jobs', 'A') },
  read_building_breakdown:   { jobId: ID('jobs', 'A') },
  read_job_pct_audit:        { jobId: ID('jobs', 'A') },
  read_active_lines:         { estimate_id: ID('estimates', 'A') },
  read_existing_clients:     { query: 'a' },
  read_existing_leads:       { query: 'a' },
  read_metrics:              { range: '7d' },
  read_recent_conversations: { limit: 20 },
  read_materials:            { q: 'a' },
  read_purchase_history:     { days: 365 },
  search_entities:           { entity_type: 'client', q: 'a' },
  search_my_kb:              { q: 'text' },
  search_org_kb:             { q: 'text' },
  search_my_sessions:        { query: 'alpha' },
  search_reference_sheet:    { q: 'a' },
  recall:                    { query: 'alpha' },
  find_entities_near:        { lat: 28.5, lng: -81.4, radius_miles: 50 },
};

// The write tools mint ids from Date.now(); they are excluded here for the same
// reason they are ledgered in test/tenant-conformance.test.js, and named rather
// than filtered by a shape guess.
const MINTS_AN_ID = ['create_property', 'remember'];

const UNKNOWN_RE = /^Unknown (?:staff |approval-tier staff |intake read |memory |Wave 3 |project-inline )?tool:/;

const ctx = () => ({
  userId: ID('users', 'A'), orgId: ORG_A,
  user: { id: ID('users', 'A'), organization_id: ORG_A, role: 'admin', email: 'a@a.a' },
});

let server, baseUrl;

async function httpGet(url, user) {
  const res = await fetch(baseUrl + url, {
    // `connection: close` is not decoration. undici keeps its sockets alive, so
    // without it the server has a live connection after the last assertion,
    // `server.close()` never calls back, and jest force-exits the worker — and
    // a force-exited worker can TRUNCATE A FAILURE REPORT. The suite would
    // still be "passing"; it just might stop being able to tell you when it
    // isn't. That is the one failure mode a guard cannot have.
    headers: { authorization: 'Bearer ' + signToken(user), connection: 'close' },
  });
  let body = null;
  try { body = await res.json(); } catch (e) { body = null; }
  return { status: res.status, body };
}

// ── WHY THE GOLDEN IS NORMALISED TOO, AND WHY REGENERATING IS NOT THE FIX ──
// This file went red on 2026-09-06 with `age 36d` against `age 37d`. No code
// changed. `read_lead_pipeline` (ai-routes.js:10221) prints
// `Math.round((Date.now() - created_at) / 86400000) + 'd'`, so one door's bytes
// advance by one every midnight. The golden was captured at 69f2cabd on a
// particular day, and that day is now in the past.
//
// THE OBVIOUS REACTION IS THE DESTRUCTIVE ONE. Re-running with
// P86_CAPTURE_GOLDEN=1 makes the red go away and, in the same stroke, replaces
// answers recorded at the PRE-REPAIR commit with answers recorded at HEAD. The
// file would still be named a golden and would still assert deep equality; it
// would simply have stopped being evidence, because it would no longer say
// anything about 69f2cabd. There is no way to re-capture it from this tree —
// the only machine that can produce it is a worktree at 69f2cabd, and the
// value of the artifact is precisely that it came from there.
//
// So the fuse is defused on the COMPARISON side, not the artifact side. The
// golden's bytes on disk are never rewritten. Both sides are pushed through
// `stable()` at compare time (see `diffDoors`), which means adding a rule here
// retro-normalises the stored answers without touching them.
//
// `stable()` must therefore be IDEMPOTENT — the golden's strings were already
// normalised once by the `stable()` of the day they were captured, and are
// normalised again now. `stable(stable(x)) === stable(x)` is asserted below.
//
// Every rule here is a hole in the differential, so each one is narrow and
// anchored. `age <N>d` is matched only after the literal word "age"; a bare
// `\d+d` would also swallow a quantity, and a rule that swallowed `$250` or
// `conf 111%` would let a repair move John's money without this file noticing.
function stable(s) {
  return String(s)
    .replace(/\d{4}-\d{2}-\d{2}([T ]\d{2}:\d{2}(:\d{2})?(\.\d+)?Z?)?/g, '<TS>')
    .replace(/\b(Mon|Tue|Wed|Thu|Fri|Sat|Sun)\b[^,\n"]{0,24}/g, '<DAY>')
    .replace(/\b\d+\s*(seconds?|minutes?|hours?|days?|weeks?|months?|years?)\s*(ago|from now)/gi, '<REL>')
    // read_lead_pipeline: ' · age ' + days + 'd'. Anchored on the word.
    .replace(/\bage \d+d\b/g, 'age <AGE>');
}

// Anything left that still looks like it was computed from the wall clock. This
// is the guard that keeps the list above honest: a NEW door that starts
// printing a computed age would otherwise sit green until the day it rolled
// over, which is the exact failure this file just had.
const CLOCK_SHAPED = [
  ['bare age',        /\bage \d+/],
  ['duration suffix', /\b\d+\s?(?:d|hr?|min|w|mo|yr)s?\b/],
  ['ago / from now',  /\b\d+[^\n]{0,12}\b(?:ago|from now)\b/i],
  ['ISO date',        /\b\d{4}-\d{2}-\d{2}\b/],
  ['month name',      /\b(?:Jan|Feb|Mar|Apr|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\b/],
];

// The one comparison, named so it can be driven directly with fabricated
// answers. A diff routine that is only ever exercised by the happy path is a
// diff routine nobody has ever seen say "different".
// It is SYMMETRIC on purpose. A door that vanished would otherwise pass by not
// being compared, and a door that APPEARED would pass by not being in the
// golden's key list at all — so both directions are the same function's job
// rather than a separate assertion someone can weaken without noticing.
function diffDoors(goldenAnswers, nowAnswers) {
  const moved = [];
  for (const k of Object.keys(goldenAnswers)) {
    // BOTH SIDES through the CURRENT stable(). The golden on disk is untouched.
    if (stable(goldenAnswers[k]) !== stable(nowAnswers[k])) {
      moved.push(k + '\n    then: ' + String(goldenAnswers[k]).slice(0, 220)
                   + '\n    now : ' + String(nowAnswers[k]).slice(0, 220));
    }
  }
  for (const k of Object.keys(nowAnswers)) {
    if (!Object.prototype.hasOwnProperty.call(goldenAnswers, k)) {
      moved.push(k + '\n    then: <ABSENT FROM THE GOLDEN — this door is new>'
                   + '\n    now : ' + String(nowAnswers[k]).slice(0, 220));
    }
  }
  return moved;
}

// ── the recording ─────────────────────────────────────────────────────────
async function record() {
  const out = {};

  // THE AGENT SURFACE.
  for (const name of publishedToolNames()) {
    if (MINTS_AN_ID.indexOf(name) !== -1) continue;
    let s;
    try { s = TWO.flatten(await I.execAgentTool(name, RECIPES[name] || {}, ctx())); }
    catch (e) { s = 'THREW: ' + (e && e.message); }
    if (s.startsWith('THREW: ') && UNKNOWN_RE.test(s.slice(7))) continue;   // not dispatched here
    out['tool:' + name] = stable(s);
  }

  // THE ADMIN CONSOLE — the surface all three of the L1/L2/L3 repairs landed on.
  const admin = { id: ID('users', 'A'), email: 'a@a.a', name: 'A Admin', role: 'admin', organization_id: ORG_A };
  for (const [label, url] of [
    ['metrics', '/api/admin/agents/metrics?range=7d'],
    ['conversations', '/api/admin/agents/conversations?limit=20'],
    ['managed', '/api/admin/agents/managed'],
    ['managed_audit', '/api/admin/agents/managed/audit'],
  ]) {
    const r = await httpGet(url, admin);
    out['route:' + label] = stable(r.status + ' ' + JSON.stringify(r.body));
  }
  return out;
}

beforeAll((done) => {
  const app = express();
  app.use(express.json({ limit: '10mb' }));
  app.use('/api/ai', aiRoutes);
  app.use('/api/admin/agents', adminAgentsRoutes);
  setRolePool(engine.pool);
  refreshRoleCache().then(() => {
    server = http.createServer(app);
    server.listen(0, '127.0.0.1', () => {
      baseUrl = 'http://127.0.0.1:' + server.address().port;
      done();
    });
  });
});
afterAll((done) => {
  // closeAllConnections FIRST. `fetch` (undici) holds its sockets open with
  // keep-alive, so `server.close()` alone waits for a connection that will
  // never end on its own and the worker never exits — which jest reports as
  // "A worker process has failed to exit gracefully" and then FORCE-EXITS,
  // and a force-exited worker can truncate a failure report. A suite whose
  // failures might not be printed is worse than a slow one.
  if (typeof server.closeAllConnections === 'function') server.closeAllConnections();
  server.close(() => done());
});

// ── CAPTURE MODE ──────────────────────────────────────────────────────────
// Set P86_CAPTURE_GOLDEN=1 to WRITE the golden instead of checking it. This is
// how the file was produced inside a `69f2cabd` worktree. It is deliberately an
// env var and not the default: a golden that regenerates itself whenever it
// disagrees is not a golden, it is a rubber stamp.
const CAPTURING = process.env.P86_CAPTURE_GOLDEN === '1';

function headSha() {
  try {
    return require('child_process')
      .execFileSync('git', ['rev-parse', '--short=8', 'HEAD'], { encoding: 'utf8' }).trim();
  } catch (e) { return ''; }
}

// ── THE GUARD ON THE ONLY DESTRUCTIVE PATH IN THIS FILE ───────────────────
// Returns a refusal message, or '' to allow the write.
//
// This exists because P86_CAPTURE_GOLDEN was set by accident during an
// unrelated experiment on 2026-09-06. The capture ran, the golden was rewritten
// with a provenance of 'UNKNOWN', and the only reason the evidence still exists
// is that git had a copy. The old code ACCEPTED a missing SHA and recorded the
// string 'UNKNOWN' — which is to say the most valuable file in this suite could
// be destroyed by setting one environment variable and running the tests.
//
// Refusing is not defensive tidiness. There is no way to re-derive this artifact
// from this tree: it can only be produced by a worktree at the pre-repair
// commit, so a bad overwrite is not a mistake you fix, it is one you restore
// from history or lose. It is a pure function so every branch can be asserted
// without spawning a capture to find out.
function captureRefusal(sha, head) {
  // Trimmed HERE, not by the caller: a guard that depends on being handed clean
  // input is a guard with a way around it.
  sha = String(sha == null ? '' : sha).trim();
  head = String(head == null ? '' : head).trim();
  if (!sha || sha === 'UNKNOWN') {
    return 'REFUSING to write the golden: P86_CAPTURE_SHA is not set.\n' +
      'The golden records what a SPECIFIC pre-repair commit answered. A capture that\n' +
      'cannot name its commit is not evidence, and writing one destroys the evidence\n' +
      'already there. Restore with:  git checkout -- ' + GOLDEN_PATH;
  }
  // A golden captured from the tree under test proves only that HEAD equals
  // itself — the exact failure this whole file exists to avoid. Refused at the
  // point of writing rather than caught later at compare.
  if (head && (head.startsWith(sha) || sha.startsWith(head))) {
    return 'REFUSING to write the golden: P86_CAPTURE_SHA (' + sha + ') is the HEAD of the\n' +
      'tree being measured. Capture must run in a detached worktree at the PRE-REPAIR\n' +
      'commit (' + PRE_REPAIR_SHA + '); a self-capture is a rubber stamp.';
  }
  return '';
}

describe('single-tenant inertness, against the pre-repair commit', () => {
  test(CAPTURING ? 'CAPTURE the golden' : 'every door answers exactly what 69f2cabd answered', async () => {
    const now = await record();

    if (CAPTURING) {
      // ── THE GUARD ON THE ONLY DESTRUCTIVE PATH IN THIS FILE ──────────────
      // This was written after `P86_CAPTURE_GOLDEN` was set by accident during
      // an unrelated experiment on 2026-09-06. The capture ran, the golden was
      // rewritten with `generated_from: 'UNKNOWN'`, and the only reason the
      // evidence still exists is that git had a copy. The old code accepted a
      // missing SHA and recorded the string 'UNKNOWN' — which is to say the
      // single most valuable file in this suite could be destroyed by setting
      // one environment variable and running the tests.
      //
      // Refusing is not defensive tidiness. There is no way to re-derive this
      // artifact from this tree: it can only be produced by a worktree at the
      // pre-repair commit, so a bad overwrite is not a mistake you fix, it is
      // one you restore from history or lose.
      const sha = (process.env.P86_CAPTURE_SHA || '').trim();
      const refusal = captureRefusal(sha, headSha());
      if (refusal) throw new Error(refusal);

      fs.mkdirSync(path.dirname(GOLDEN_PATH), { recursive: true });
      fs.writeFileSync(GOLDEN_PATH, JSON.stringify({
        generated_from: sha,
        note: 'Captured by running this file inside a detached worktree at the named commit. Do NOT regenerate from HEAD.',
        answers: now,
      }, null, 1) + '\n');
      expect(Object.keys(now).length).toBeGreaterThan(40);
      return;
    }

    const golden = JSON.parse(fs.readFileSync(GOLDEN_PATH, 'utf8'));

    // A golden captured from HEAD proves only that HEAD equals itself.
    expect(golden.generated_from).toBe(PRE_REPAIR_SHA);

    // Per DOOR, never a rate: the diff names every door whose bytes moved.
    const moved = diffDoors(golden.answers, now);
    expect(moved).toEqual([]);

    // And nothing appeared or vanished. A door that stopped answering would
    // otherwise pass the loop above by not being compared at all.
    expect(Object.keys(now).sort()).toEqual(Object.keys(golden.answers).sort());
  }, 120000);

  test('the golden covers both surfaces, and says how many doors', () => {
    if (CAPTURING) return;
    const golden = JSON.parse(fs.readFileSync(GOLDEN_PATH, 'utf8'));
    const keys = Object.keys(golden.answers);
    expect(keys.filter((k) => k.startsWith('tool:')).length).toBeGreaterThan(40);
    // The four admin-console doors the L1/L2/L3 repairs landed on.
    expect(keys.filter((k) => k.startsWith('route:')).sort())
      .toEqual(['route:conversations', 'route:managed', 'route:managed_audit', 'route:metrics']);
  });

  test('the un-stamped legacy row is PRESENT — without it the tolerance arm is never exercised', () => {
    const rows = engine.all('SELECT organization_id FROM ai_messages');
    expect(rows.some((r) => r.organization_id === null)).toBe(true);
    expect(rows.some((r) => r.organization_id === ORG_A)).toBe(true);
  });
});

// ── THE PROPERTIES OF THE COMPARISON ITSELF ───────────────────────────────
// These drive `diffDoors` and `stable` with fabricated answers, so they hold
// whatever the database says and whatever day it is. The point of the group is
// that the differential must be BOTH deaf to the calendar AND still able to
// shout — a normaliser can always be made to pass by normalising everything.
describe('the differential is clock-independent, and still differential', () => {
  test('stable() is idempotent — the golden is normalised a second time at compare', () => {
    // The stored answers were normalised once, by the stable() of the day they
    // were captured; diffDoors normalises them again. If a rule were not a
    // fixed point, that second pass would silently rewrite the evidence.
    const golden = JSON.parse(fs.readFileSync(GOLDEN_PATH, 'utf8'));
    for (const [door, v] of Object.entries(golden.answers)) {
      expect([door, stable(stable(v))]).toEqual([door, stable(v)]);
    }
  });

  test('an age that advanced overnight is NOT a moved door', () => {
    // The literal failure of 2026-09-06, reduced.
    const then = '- A · active · conf 111% · $0K-$0K · src web · age 36d';
    const now  = '- A · active · conf 111% · $0K-$0K · src web · age 37d';
    expect(diffDoors({ 'tool:read_lead_pipeline': then },
                     { 'tool:read_lead_pipeline': now })).toEqual([]);
    // and any other day, including three-digit ages and a same-day zero.
    for (const d of [0, 1, 9, 99, 100, 4821]) {
      expect(diffDoors({ d: 'age 36d' }, { d: 'age ' + d + 'd' })).toEqual([]);
    }
  });

  // ── THE FUSE THE SCRUBBER CANNOT REACH ──────────────────────────────────
  // `stable()` defuses a printed duration. It cannot defuse the other half of
  // this class, and the two tests below are the half it cannot reach.
  //
  // When a seeded row ages out of a window the query measures against NOW(),
  // what moves is not a token that changed SHAPE — it is a COUNT that changed
  // VALUE. `turns: 1` becomes `turns: 0`. No normaliser may touch that: the
  // MONEY test directly below is the standing promise that a figure moving is
  // always a failure, so the fixture has to be held in band instead.
  //
  // Measured, not assumed. With the anchors pinned to literals, moving the
  // ai_messages seed two days further back turned four doors red at once —
  // tool:read_metrics, tool:read_recent_conversations, route:metrics and
  // route:conversations — and every clock-shaped guard in this file stayed
  // green while it happened.
  test('the fixture anchors are OFFSETS FROM NOW, not calendar dates', () => {
    // The regression is re-pinning an anchor to a literal. A literal is stable
    // between two runs on one afternoon, which is exactly why it survives
    // review; it is the passage of DAYS that breaks it. So the clock is
    // injected rather than waited for.
    const t1 = Date.parse('2026-09-07T12:00:00Z');
    const t2 = t1 + (365 * TWO.DAY_MS);
    expect(TWO.daysAgo(5, t1)).toBe('2026-09-02 12:00:00');
    expect(TWO.daysAgo(5, t2)).toBe('2027-09-02 12:00:00');
    // The age is what is constant. The date is not, and must not be.
    expect(TWO.daysAgo(5, t1)).not.toBe(TWO.daysAgo(5, t2));
    for (const n of [0, 1, 5, 36, 180, 4821]) {
      expect([n, Math.round((t1 - Date.parse(TWO.daysAgo(n, t1).replace(' ', 'T') + 'Z')) / TWO.DAY_MS)])
        .toEqual([n, n]);
    }
  });

  test('the seeded rows are a FIXED AGE, inside the windows the golden was captured in', () => {
    // Asserted as an EXACT age rather than as a band, so re-pinning an anchor
    // to a literal fails on the next run instead of on the day the drift
    // finally crosses a boundary. A band alone would have let '2026-08-01' sit
    // here for another five months before the 180-day lookback noticed.
    //
    // The tolerance is ~14 minutes: these are computed at module load and read
    // back a few seconds later, and nothing here may care about those seconds.
    const ageDays = (v) => (Date.now() - Date.parse(v)) / TWO.DAY_MS;
    const isAbout = (v, n) => Math.abs(ageDays(v) - n) < 0.01;

    // read_metrics, read_recent_conversations, route:metrics and
    // route:conversations all read these back through `datetime('now','-7
    // days')`, and the golden records them as COUNTED — so: 5 days, inside 7.
    const msgs = engine.all('SELECT id, created_at FROM ai_messages');
    expect(msgs.length).toBeGreaterThan(0);
    for (const r of msgs) {
      expect([r.id, isAbout(r.created_at, 5), ageDays(r.created_at) < 7])
        .toEqual([r.id, true, true]);
    }

    // read_existing_leads looks back 180 days and the golden records "Matches
    // found: 2". The 30-day floor is the other edge: the golden was captured
    // with these leads already outside every 30-day window, and a row drifting
    // back inside one moves a count just as loudly as one drifting out.
    const leads = engine.all('SELECT id, created_at FROM leads');
    expect(leads.length).toBeGreaterThan(0);
    for (const r of leads) {
      const a = ageDays(r.created_at);
      expect([r.id, isAbout(r.created_at, 36), a > 30 && a < 180])
        .toEqual([r.id, true, true]);
    }

    // And the anchor itself, so a re-pin is named at its source rather than
    // only through the rows it seeded.
    expect(['T_OLD', isAbout(TWO.T_OLD.replace(' ', 'T') + 'Z', 36)]).toEqual(['T_OLD', true]);
  });

  test('MONEY still moves the differential — the normaliser must not swallow it', () => {
    // The whole point of the file is that a repair must not change what John
    // sees. If normalisation ate a figure, it would pass while doing so.
    const pairs = [
      ['$0K-$0K', '$1K-$0K'],
      ['conf 111%', 'conf 112%'],
      ['active=2 ($0K)', 'active=1 ($0K)'],
      ['phaseBudget 1000', 'phaseBudget 1001'],
      ['amount 150', 'amount 151'],
      ['· age 36d · $250', '· age 36d · $260'],
    ];
    for (const [a, b] of pairs) {
      expect([a, b, diffDoors({ k: a }, { k: b }).length]).toEqual([a, b, 1]);
    }
  });

  test('a door that changes, VANISHES or APPEARS is caught — both directions', () => {
    expect(diffDoors({ k: 'alpha' }, { k: 'beta' }).length).toBe(1);   // changed
    expect(diffDoors({ k: 'alpha' }, {}).length).toBe(1);              // vanished
    expect(diffDoors({}, { k: 'alpha' }).length).toBe(1);              // appeared
    expect(diffDoors({}, { k: 'alpha' })[0]).toMatch(/ABSENT FROM THE GOLDEN/);
    expect(diffDoors({ a: '1' }, { b: '1' }).length).toBe(2);          // one of each
    expect(diffDoors({ k: 'alpha' }, { k: 'alpha' })).toEqual([]);     // unchanged
    // an undefined answer is not silently equal to a missing one
    expect(diffDoors({ k: 'alpha' }, { k: undefined }).length).toBe(1);
  });

  test('NO answer in the golden still carries a clock-shaped token after normalisation', () => {
    // The guard that keeps `stable()` current. A new door that begins printing
    // a computed age would otherwise be green until the night it rolled over —
    // which is exactly how this suite failed. Named PER DOOR, never a count.
    const golden = JSON.parse(fs.readFileSync(GOLDEN_PATH, 'utf8'));
    const dirty = [];
    for (const [door, v] of Object.entries(golden.answers)) {
      const s = stable(v);
      for (const [label, re] of CLOCK_SHAPED) {
        const m = s.match(re);
        if (m) dirty.push(door + ' :: ' + label + ' :: ' + JSON.stringify(m[0]));
      }
    }
    expect(dirty).toEqual([]);
  });

  test('the LIVE recording is clock-shaped-free too, not just the stored golden', async () => {
    // The golden is frozen; the live side is what actually moves. Asserting
    // only against the file would let a newly-added door rot undetected.
    const now = await record();
    const dirty = [];
    for (const [door, v] of Object.entries(now)) {
      const s = stable(v);
      for (const [label, re] of CLOCK_SHAPED) {
        const m = s.match(re);
        if (m) dirty.push(door + ' :: ' + label + ' :: ' + JSON.stringify(m[0]));
      }
    }
    expect(dirty).toEqual([]);
  }, 120000);

  test('capture mode REFUSES to run without a named commit — and the bytes survive', () => {
    // Behavioural, not structural: a real child jest is started with
    // P86_CAPTURE_GOLDEN=1 and no P86_CAPTURE_SHA — the exact accident that
    // overwrote this golden on 2026-09-06 — and the file's bytes are compared
    // before and after. If the guard is ever removed this test fails AND puts
    // the bytes back, so the test that protects the evidence can never be the
    // thing that destroys it.
    const before = fs.readFileSync(GOLDEN_PATH);
    const cp = require('child_process');
    const r = cp.spawnSync(process.execPath, [
      // NOT require.resolve — jest sandboxes the resolver inside a test file.
      path.join(__dirname, '..', 'node_modules', 'jest', 'bin', 'jest.js'),
      '--roots=./test', '--testPathPatterns', 'tenant-noop-differential',
      '-t', 'CAPTURE the golden',
    ], {
      cwd: path.join(__dirname, '..'),
      encoding: 'utf8',
      env: Object.assign({}, process.env, {
        P86_CAPTURE_GOLDEN: '1',
        P86_CAPTURE_SHA: '',
      }),
      timeout: 120000,
    });
    const after = fs.readFileSync(GOLDEN_PATH);
    if (!after.equals(before)) fs.writeFileSync(GOLDEN_PATH, before);   // put it back, always

    expect(after.equals(before)).toBe(true);
    expect(r.status).not.toBe(0);
    expect(String(r.stdout) + String(r.stderr)).toMatch(/REFUSING to write the golden/);
  }, 180000);

  test('capture mode is OFF by default, and the guard precedes the write', () => {
    // The default matters more than the guard: a golden that regenerates itself
    // whenever it disagrees is a rubber stamp, and the guard is only reached if
    // someone has already opted in.
    expect(CAPTURING).toBe(false);
    const src = fs.readFileSync(__filename, 'utf8');
    const branch = src.slice(src.indexOf('if (CAPTURING) {'));
    const guard = branch.indexOf('captureRefusal(');
    const write = branch.indexOf('fs.writeFileSync(GOLDEN_PATH');
    expect(guard).toBeGreaterThan(-1);
    expect(write).toBeGreaterThan(guard);                // guard precedes the write
    // The recorded provenance is the VALIDATED sha, never a fallback literal.
    expect(branch).toMatch(/generated_from: sha,/);
    expect(branch).not.toMatch(/generated_from:[^\n]*\|\|/);
  });

  test('captureRefusal: every branch, without spawning a capture to find out', () => {
    // A missing, blank or placeholder provenance is refused.
    for (const bad of ['', '   ', 'UNKNOWN']) {
      expect([bad, /^REFUSING/.test(captureRefusal(bad, 'a7ca98f4'))]).toEqual([bad, true]);
    }
    // Capturing at the tree's own HEAD is refused, in either abbreviation.
    expect(captureRefusal('a7ca98f4', 'a7ca98f4')).toMatch(/is the HEAD/);
    expect(captureRefusal('a7ca98f4f37b', 'a7ca98f4')).toMatch(/is the HEAD/);
    expect(captureRefusal('a7ca98f4', 'a7ca98f4f37b')).toMatch(/is the HEAD/);
    // A real pre-repair capture, from a worktree at another commit, is allowed.
    expect(captureRefusal(PRE_REPAIR_SHA, 'a7ca98f4')).toBe('');
    // No git available: the SHA check still stands, the HEAD check cannot.
    expect(captureRefusal('', '')).toMatch(/^REFUSING/);
    expect(captureRefusal(PRE_REPAIR_SHA, '')).toBe('');
  });

  test('CLOCK_SHAPED actually detects clock-shaped text — the guard is not empty', () => {
    // A guard list that has been emptied still passes every test that only asks
    // "did it find anything?". So it is asked the opposite question too.
    expect(CLOCK_SHAPED.length).toBeGreaterThan(0);
    const caught = (s) => CLOCK_SHAPED.some(([, re]) => re.test(s));
    for (const s of ['age 36d', 'age 0', '· age 412d', '2026-09-01', '14 days ago',
                     '3 hrs from now', 'Sep 2026', '7d', '30 min']) {
      expect([s, caught(s)]).toEqual([s, true]);
    }
    // and does not fire on the things the differential must keep watching
    for (const s of ['$250', 'conf 111%', '<TS>', '<DAY>', '<REL>', 'age <AGE>',
                     'phaseBudget 1000', 'active=2 ($0K)']) {
      expect([s, caught(s)]).toEqual([s, false]);
    }
  });
});
