// Web Push subscription API (S7).
//
//   GET  /api/push/public-key   → { key, configured } (key null until VAPID env set)
//   POST /api/push/subscribe    → body: the PushSubscription JSON from the browser
//   POST /api/push/unsubscribe  → body: { endpoint }
//
// All authed; rows are scoped to the caller. The client toggle lives in the
// Background Tasks panel (js/agent-tasks.js) and hides itself when unconfigured.

const express = require('express');
const { pool } = require('../db');
const { requireAuth } = require('../auth');
const push = require('../push');

const router = express.Router();
console.log('[push-routes] mounted at /api/push');

router.use(requireAuth);

// GET /api/push/events — the notification catalog (what each event says + which
// channels it rides) plus the caller's current prefs. Drives the My Account UI.
router.get('/events', async (req, res) => {
  try {
    const { NOTIFY_EVENTS } = require('../notify-events');
    await push.ensureInit();   // lazy VAPID init — without this a fresh process reports configured:false
    const r = await pool.query('SELECT notification_prefs FROM users WHERE id = $1', [req.user.id]);
    res.json({
      events: NOTIFY_EVENTS,
      prefs: (r.rows[0] && r.rows[0].notification_prefs) || {},
      push_configured: push.isConfigured()
    });
  } catch (e) {
    console.error('GET /api/push/events error:', e);
    res.status(500).json({ error: 'Failed to load notification catalog' });
  }
});

router.get('/public-key', async (req, res) => {
  // ensureInit self-generates + persists a VAPID pair on first call if no env
  // override exists — so this endpoint flips to configured:true on its own.
  const key = await push.getPublicKey();
  res.json({ key: key, configured: push.isConfigured() });
});

router.post('/subscribe', async (req, res) => {
  try {
    const sub = req.body || {};
    const endpoint = String(sub.endpoint || '');
    const keys = sub.keys || {};
    if (!endpoint.startsWith('https://') || !keys.p256dh || !keys.auth) {
      return res.status(400).json({ error: 'Invalid push subscription' });
    }
    const ua = String(req.headers['user-agent'] || '').slice(0, 300);
    // RE-POINTING A SUBSCRIPTION NOW COSTS THE DEVICE, NOT THE ENDPOINT STRING.
    //
    // This was `ON CONFLICT (endpoint) DO UPDATE SET user_id = EXCLUDED.user_id`
    // with no condition, and the shared-device rationale for it is REAL and is
    // preserved below: one phone gets handed between crew, the second person
    // signs in, the browser hands back the subscription the first person's
    // session created, and that row MUST follow the current user or the wrong
    // person keeps getting the notifications.
    //
    // What the unconditional form also allowed, executed rather than reasoned:
    // a user who merely KNEW another user's endpoint string POSTed it here with
    // keys of their own and took the row over — user_id moved, keys replaced,
    // HTTP 200 — and the victim silently stopped receiving notifications, with
    // nothing on any screen to say why. push_subscriptions has no
    // organization_id, so it is not even cross-tenant in a sense the org
    // invariant can see; it is cross-USER, across every tenant at once.
    //
    // The line drawn: the endpoint NAMES the subscription, the keys PROVE it.
    // p256dh and auth are generated by the browser for that subscription and
    // are not derivable from the endpoint, so presenting the stored pair is
    // evidence of holding the actual device. A takeover is allowed when the
    // caller can present them, and refused when they cannot. Both legitimate
    // shared-device flows still land: the browser that returns an existing
    // subscription returns its keys with it (matching pair → re-pointed), and
    // a browser that resubscribed from scratch has a NEW endpoint, which does
    // not conflict at all. Refreshing your OWN row is always allowed, so a
    // genuine key rotation on an unchanged endpoint is not locked out.
    //
    // WHAT AN ATTACKER CAN STILL DO, stated so the next reader does not have
    // to rediscover it: anyone holding BOTH the endpoint and its current key
    // pair can still re-point the row. That is not a weaker rule than it
    // looks — with those values they can already push to the device directly,
    // without this endpoint — but it does mean the keys must be treated as
    // secrets, and any future surface that returns a subscription's keys to a
    // client reopens this.
    const { rows } = await pool.query(
      `INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth, user_agent)
       VALUES ($1, $2, $3, $4, $5)
       ON CONFLICT (endpoint) DO UPDATE
         SET user_id = EXCLUDED.user_id, p256dh = EXCLUDED.p256dh,
             auth = EXCLUDED.auth, user_agent = EXCLUDED.user_agent
       WHERE push_subscriptions.user_id = EXCLUDED.user_id
          OR (push_subscriptions.p256dh = EXCLUDED.p256dh
              AND push_subscriptions.auth = EXCLUDED.auth)
       RETURNING user_id`,
      [req.user.id, endpoint, String(keys.p256dh).slice(0, 300), String(keys.auth).slice(0, 300), ua]
    );
    // A refused re-point must be VISIBLE. Answering 200 here would tell the
    // client it is subscribed while the notifications keep going to someone
    // else — the same "success that wrote nothing" this codebase keeps
    // finding. 409 rather than 404: the row exists, the caller just has not
    // shown they hold it, and the fix on the client is to unsubscribe and
    // resubscribe, which yields a fresh endpoint that inserts cleanly.
    if (!rows.length) {
      return res.status(409).json({
        error: 'That push endpoint belongs to a different subscription on this device. ' +
               'Unsubscribe and resubscribe to register a new one.'
      });
    }
    res.json({ ok: true });
  } catch (e) {
    console.error('POST /api/push/subscribe error:', e);
    res.status(500).json({ error: 'Failed to save subscription' });
  }
});

router.post('/unsubscribe', async (req, res) => {
  try {
    const endpoint = String((req.body && req.body.endpoint) || '');
    if (!endpoint) return res.status(400).json({ error: 'endpoint required' });
    await pool.query('DELETE FROM push_subscriptions WHERE endpoint = $1 AND user_id = $2', [endpoint, req.user.id]);
    res.json({ ok: true });
  } catch (e) {
    console.error('POST /api/push/unsubscribe error:', e);
    res.status(500).json({ error: 'Failed to remove subscription' });
  }
});

module.exports = router;
